# Generated by Django 2.2.3 on 2019-07-24 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realtor',
            old_name='emial',
            new_name='email',
        ),
    ]
